# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages: devtools

r:
- 3.2
- 3.3
- 3.4
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'
